version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wangzc:latest
    container_name: flask_app
    volumes:
      - /data:/data
    ports:
      - "6090:6090"
    environment:
      - PATH=/opt/conda/envs/flask2024/bin:$PATH

